### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: Trap Kit

# Write a short description for the site. This is used for "meta description."
description: No-cost, no-catch rapid web prototyping for no-coders

# Enable for live hosting on GitHub Pages
# This should match the name of your GitHub repository, along with a leading forward slash (/).
# baseurl: /trapkit

# Enable for live hosting on GitHub Pages with a custom domain
# This should match the full domain name that loads in your browser, along with a trailing forward slash (/).
url: https://trapkit.co/

### RECOMMENDED SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]

# Remove generation of additional style.css
theme: null

# Tell Jekyll where you're going to keep your collection content files.
collections_dir: collections

# Define collections for use with rich text-based components.
# For each collection, create a folder with that name, PRECEDED BY AN UNDERSCORE (e.g., _borrowing and _charters).
collections:
  - borrowing
  - charters